AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  discord-video-webhook-stack

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters: 
  BucketName: 
    Description: Name of s3 bucket
    Type: String
  WebhookUrl:
    Description: Discord webhook to be triggered in lambda
    Type: String

Resources:
  ClipBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      # This template was created without specifying the notification configuration, then updating with a notification configuration
      # See here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfiguration.html 
      # NotificationConfiguration:
      #   LambdaConfigurations:
      #     - Event: 's3:ObjectCreated:*'
      #       Function: !Ref S3EventNotificationFunction
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  S3EventNotificationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: CallDiscordWebhook/
      Handler: app.lambda_handler
      Runtime: python3.9
      Timeout: 5
      Environment:
        Variables:
          WEBHOOK_URL: !Ref WebhookUrl
      Architectures:
        - x86_64
      # Events:
      #   S3Event:
      #     Type: S3 # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Bucket:
      #         Ref: ClipBucket
      #       Events:
      #         - 's3:ObjectCreated:*'
      #       # Filter: 
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17' 
          Statement:
            - Effect: Allow
              Action: 
                - "s3:GetObject"
              Resource: !Join 
                  - ''
                  - - !GetAtt ClipBucket.Arn
                    - /*
            - Effect: Allow
              Action: 
                - "s3:ListObject"
              Resource: !GetAtt ClipBucket.Arn

Outputs:
  BucketName:
    Value: !Ref ClipBucket
    Description: Name of the bucket